security:
   encoders:
       FOS\UserBundle\Model\UserInterface: sha512

   role_hierarchy:
       ROLE_ADMIN:       ROLE_USER
       ROLE_SUPER_ADMIN: ROLE_ADMIN

   providers:
       fos_userbundle:
           id: fos_user.user_provider.username

   firewalls:
       main:
           pattern: ^/
           form_login:
               check_path: fos_user_security_check
               login_path: fos_user_security_login
               provider: fos_userbundle
               csrf_provider: security.csrf.token_manager

           logout:
               path:    fos_user_security_logout
               target: /
               #  csrf_provider: form.csrf_provider
               #  provider: fos_userbundle

           anonymous:    true


   access_control:
       - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/admin/, role: ROLE_ADMIN }
       - { path: ^/logout/, role: ROLE_ADMIN }
       - { path: ^/login_check/, role: ROLE_ADMIN }
