# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
   post_type:
      class: MyApp\CoreBundle\Form\PostType
      tags:
         -  { name: post.type }
