<?php
namespace MyApp\CoreBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{

}
